<?php echo $this->headTitle('Posts - '); ?>
<div class="container">

    <h3>Posts</h3><hr>

    <a href="<?= $this->url(array('controller'=>'post', 'action'=>'create'), 'default', true)?>" class="btn btn-info"><i class="glyphicon glyphicon-plus"></i> Adicionar</a><br><br>

    <table class="table table-bordered table-striped">
        <tr>
            <th>Titulo</th>
            <th>Descrição</th>
            <th></th>
        </tr>
        <?php foreach( $this->posts as $post): ?>
            <tr>
                <td><?= $post['title'] ?></td>
                <td><?= $post['description'] ?></td>
                <td>
                    <a href="<?= $this->url(array('controller'=>'post', 'action'=>'show', 'id' => $post['id']), 'default', true ) ?>" class="btn btn-info btn-xs" title="Ver"><i class="glyphicon glyphicon-eye-open"></i> </a>
                    <a href="<?= $this->url(array('controller'=>'post', 'action'=>'update', 'id' => $post['id']), 'default', true ) ?>" class="btn btn-info btn-xs" title="Editar"><i class="glyphicon glyphicon-pencil"></i> </a>
                    <a href="<?= $this->url(array('controller'=>'post', 'action'=>'delete', 'id' => $post['id']), 'default', true ) ?>" class="btn btn-info btn-xs confirm-action"
                       data-message="Deseja excluir este post?" title="Excluir"><i class="glyphicon glyphicon-trash"></i> </a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>

</div>